---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: argocd
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgBcQI3MdJM/DNaJy2J2b4RuaQ3ecjYl0RcmQWOpAkd6OP0MH4uGCq8Xc9GWt8ICitGXBCgtKhzfRe2TIZzDQ4t+FpmoG9LDylg+7LeE7FSkbWl0oPncG+hf9eHXwWf+Y3ND7XDY+pp/bL909XadFOVRisRmIv6vqNSw7DRfxr/i0k7Ak1M0kDCy8vrZRHn1ld3qmuC09LbBr9jovGWm9AtOsKgRgweHp5u1NZAQ24TbDDy+UBwj55GTTktTNcccyh+5keIB5WabjsLj3GUU8rCE04j/o8h9q1xWUEQj3A9eAVDzBA1cqwIuLSieseby+PWS3aU/r5ajBbrpccp+bGiTgfAXs4uYPemQ5jklqqY2upiA/qWwP310MYWUG7QCYfypXTR7CQ+8FKNYDK7mWfRoaBP77wRSJRU7HoxRXb/JaUMkAwrP/VkdTE5C4mIT/HV0ZihWFwEiNKTy8+ty1j3k891Ovf3SyOXTH3x0IfXNWxzrXBXfF1NiJpJTGGNq94rmYep1cByKEvP/54ebjeutZgQ+kJb1AJ8o5kOb/oNTJTDl/aDTIiejL9g8tlljvgk5/96ryxs96X1VLcQqlnIWnT/f5WSTCOxUCp0Q9aR6G+n+uqmkK7Z8aHIeaSWTkhYgLcmDJ8oKcFBj9x+qS6DZWl4H9MxOFrLIcYJ/r5pnI54j0wo5r7DQkEPQEboVcDwoNQU6GRzdbg==
    N8N_ENCRYPTION_KEY: AgC4XMskh458i/bci5H+BcBDq/RYMbCEZgl85rDnkdLvZToaWVshObwtVoslz1v5mkw+8Wl4AiQ0Xm7UXhNKK2ZF1x3mGyqRm0F4a2ZFbNkGuFXGUrHBzMio3tq6ExMgGoBKsmOIcnPvvfwIksmDbWS3xYF3N8JudIe3SHESYosu8axYA1OF1ylCJKJTxePBZUFexnApusDNRZzya1mnbMEMz2mZeORSKbYpqt4x1kSnBC0or5g5MxRZYfGJJ+31rt5r95tm/xyd6zH9BOGTcYNaev0X7oagzcqggNNrdsnW0A+quCUtq5M7SAOamIsQ+A7lHKT/Oox7LoE86eXHWZlp69VSxGR560GKC9ptaB1UNgNX4GDDrPbSjgiEiB5wIAxHd7DXACfITSfCpNt1toXuuOWCipL0QXkN0RV+6+Mcy7qsU7FqCDpRwrV7zy2IvHfDnVTR42YnH8aQyiCn016WJRodYRIZW+xX8hiDBNYD7+iKqTbDyGg53rGkzS9HJu12sAcRlPBB4cwor7Xrdzj6pvRvZ4iBXYc5pJgZ0McKCta1BcybZEo4jk70fzkzPokz5X8QAeDPrB1l/a91Oeviy0NdkANXGmJN0HKtAAiTHpK4Hm4pQuPZd4Y7XoNfAnocO+DzGbxYMDKBfRCS8RxBy046UzDMALs9XlI9oisQDQQ+h7SB9sPyJuUbh0PNgwNSlhisN6gA0DXfhNlQCwK7eqYWhyKInulaDU/BQGUK+gHzyyD0YNWxXiGijA==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: argocd
