---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: argocd
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgDDvyuqnh/DSGPac3U0ZdeIGjNeZB0PbZym9pzhyBAjk6pcCGxnR1xj/rFrgZk5heKtQQ9nzueEuZ95yIb3H+gJce8aXFDUsrYcF+aPYZ/XHCGoxLMrVa62HdWXAHecW17VkSpAZvZdxFKioqcvPeo/A6Oppwd8jq4NdTRzNdCb7T5I85dMSz+YhoB3K/DWMy7j34fZahS3vAHNUAlXYTXP8AXhMxOg/0huX0zpye12+lATLQWF8N+KmSpLMC+HqdRNoQ4h8fnu2AGDHiNBt46C2F9hJSCLVASf2a3QpV4mq9ZUVq+ipY4uCNXqA2gisncRxahE+51Yc5WK460umR4G/xo8nruN1WLWgOI8jSSyg7HiR13wys+F8qKMKEkwWQ+hrEI/1c2a6jvadBVuzpeJro1PwDxhHZz9WP8NKQXoG38TIcCqArJVoJMqEBm2Bwffa+UJagAzcW5rLLe64w8tLil/Y9UnLj8+ovoY2I4ppGQl7076heGtQaCLmzfNb1Rmw1pMcdH8rJSec6Gg+WMbQow2Q1EZObjWKfm/uk4iKAHP62LE0z7gLQwTS9TWX+i5W8NaU/XMlNyWpqYAth4sBgwGwxNhMJQfmHaxytk67SGMrPRAauITcZAIv1F5ajhMh/I2EjCIutd0x2xrPE/JBj+xkVpcBE01npuGXgHtAMiKF9o82ZZIg1dIuOyxyptdeH1MxOJhAg==
    N8N_ENCRYPTION_KEY: AgDLyMgpVgaZsUwKBPyzWbYa3pcEpGUmDZ3bT6p2EXtOeziBkdrjCh6n+t1d7T4HzdIAeymNct/8dJQh2S2YPTJBA63g4iU0l7whCqBJ9GMZBO8eAuovJH9HRjx7Xu9RHVHbayNCgWu0jTqGcDJ/CHZ4c+gEuPdxJCUkWJMMngPFRc0DltTeCVa9oKT0TW78SsENTWJ9T6OuKHDAx3u49nseyTjPxV/e/el+SuGi0UOJp0xkoovdexYGNcj4RW3eesE5RRjnmgUjhkhoGxEkKl+qXQotxG7VmljwhN3VavxWJgul/phuGPPOlnddJAJS2AWaKIhZZnEA3++pMrSZc5NfKcFscXJFSHJXFG/zvnpJK/X7ScsQowUsdEZZo6wgRTFIWYm3zPdQm2E4Paa+BCV8pv5YEjyDV++G2mn5aqzJ3SKkjw0CefNY6fgxSSQN4iKCjcm8U645k4fRmszRlqQk+yh9Q4JNnbR4EYfVhZ678UftPZiqUKURvO38KLT525GOGyKxuYKqO2q6vhNFQjvKaVOktiG60SpPS/LHRHyhDo360dBbKOa9RPmPiZtIaTClqALSErO/AFdTTTkmoagzRYeet4+gLgAxFyLe837WXu8Ea2s7tQiBnN0nhGa57FZ95CQ52IJdcCPJ/8Z9HmRiTwBxBxy9WJYYBn7UQojj8r5MJ1W/ro/VO9xOiL8DM1ojwv4vdybiIEOSiQOtPy6yRxVD8/1m6/tcKUByyf4MwYAjF330m1y+GGvNmg==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: argocd
