apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-dev
  namespace: argocd
  labels:
    app: n8n-dev
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - julionogueira.net
      secretName: n8ndev-net-tls
  rules:
    - host: julionogueira.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n-dev
                port:
                  number: 5678
